echo()
print_r()
die()
explode(string $separator, string $string[,int $limit])
implode(string $str, array $arr)
htmlspecialchars(string $str, ……)
strip_tags(string $str, ,,,,)
ltrim()
nl2br()
md5()
sha1()
str_replace()
number_format()
substtr()
icon()
iconv_substr()
